kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "nodejs-pipeline"
spec:
  source:
    git:
      uri: "http://hit.tsoftlatam.com:3003/sre/nodejs-teom.git"
      ref: SRE-68
    sourceSecret:
      name: gitlabnodejsteom
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: openshift/Jenkinsfile
  triggers:
  - gitlab:
      secretReference:
        name: gitlab