apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: teom-ez
  template:
    metadata:
      labels:
        app: teom-ez
    spec:
      containers:
      - name: teom-ez
        image: jhonjcastroh/teom-ez:develop
        ports:
        - containerPort: 80