apiVersion: v1
kind: ReplicationController
metadata:
  name: teom-ez
  labels:
    name: teom-ez
spec:
  replicas: 3
  selector:
    name: teom-ez
  template:
    metadata:
      labels:
        name: teom-ez
    spec:
      containers:
      - name: teom-ez
        image: jhonjcastroh/teom-ez:develop
        ports:
        - containerPort: 3000
        env:
          - name: WAIT_HOSTS
            value: mongodb
          - name: WAIT_HOSTS_TIMEOUT
            value: 300
          - name: WAIT_SLEEP_INTERVAL
            value: 5
          - name: DB_USER
            value: teom
          - name: DB_PASSWORD
            value: teom*admin
          - name: DB_HOST
            value: mongodb
          - name: DB_PORT
            value: 27017
          - name: DB_NAME
            value: indicators
          - name: ELASTIC_APM_SERVICE_NAME
            value: nodejs-teom-local
          - name: ELASTIC_APM_SECRET_TOKEN
            value: APMelasticTsoft2020
          - name: ELASTIC_APM_SERVER_URL
            value: http://elkcl.tsoftglobal.com:8200/

      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        volumeMounts:
        - mountPath: /data/db
          name: mongodb-data
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: teom
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: teom*admin
          - name: MONGO_INITDB_DATABASE
            value: indicators
      volumes:
      - name: mongodb-data
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: teom-ez-svc
  labels:
    name: teom-ez
spec:
  type: NodePort
  ports:
  - port: 3000
    nodePort: 30257
  selector:
    name: teom-ez