apiVersion: v1
kind: ReplicationController
metadata:
  name: teom-ez
  labels:
    name: teom-ez
spec:
  replicas: 3
  selector:
    name: teom-ez
  template:
    metadata:
      labels:
        name: teom-ez
    spec:
      containers:
      - name: teom-ez
        image: jhonjcastroh/teom-ez:develop
        ports:
        - containerPort: 3000
        environment:
          - 'WAIT_HOSTS=mongodb:27017'
          - 'WAIT_HOSTS_TIMEOUT=300'
          - 'WAIT_SLEEP_INTERVAL=5'
          - 'DB_USER=teom'
          - 'DB_PASSWORD=teom*admin'
          - 'DB_HOST=mongodb'
          - 'DB_PORT=27017'
          - 'DB_NAME=indicators'
          - 'ELASTIC_APM_SERVICE_NAME=nodejs-teom-local'
          - 'ELASTIC_APM_SECRET_TOKEN=APMelasticTsoft2020'
          - 'ELASTIC_APM_SERVER_URL=http://elkcl.tsoftglobal.com:8200/'
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        volumes:
          - 'mongodb-data:/data/db'
        environment:
          - 'MONGO_INITDB_ROOT_USERNAME=teom'
          - 'MONGO_INITDB_ROOT_PASSWORD=teom*admin'
          - 'MONGO_INITDB_DATABASE=indicators

---
apiVersion: v1
kind: Service
metadata:
  name: teom-ez-svc
  labels:
    name: teom-ez
spec:
  type: NodePort
  ports:
  - port: 3000
    nodePort: 30257
  selector:
    name: teom-ez