apiVersion: v1
kind: ReplicationController
metadata:
  name: teom-ez
  labels:
    name: teom-ez
spec:
  replicas: 3
  selector:
    name: teom-ez
  template:
    metadata:
      labels:
        name: teom-ez
    spec:
      containers:
      - name: teom-ez
        image: jhonjcastroh/teom-ez:develop
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: teom-ez-svc
  labels:
    name: teom-ez
spec:
  type: NodePort
  ports:
  - port: 3000
    nodePort: 30257
  selector:
    name: teom-ez